import Head from 'next/head'
import About from '../layout/About'
import Clients from '../layout/Clients'
import Contact from '../layout/Contact'
import CraftAcademy from '../layout/CraftAcademy'
import Hero from '../layout/Hero'
import Process from '../layout/Process'
import Technologies from '../layout/Technologies'
import Footer from '../layout/Footer'

const Home = () => {
  return (
    <div className='home-container'>
      <Head>
        <title>Create Next App</title>
        <meta name='description' content='Generated by create next app' />
        <link rel='icon' href='/favicon.ico' />
      </Head>
      <Hero />
      <Process />
      <CraftAcademy />
      <Clients />
      <Technologies />
      <About />
      <Contact />
      {/* <Footer /> */}
    </div>
  )
}

export default Home
