import Head from 'next/head';
import Footer from '../components/footer/footer';

export default function Home() {
  return (
    <div>
      <Head>
        <title>Create Next App</title>
        <meta name='description' content='Generated by create next app' />
        <link rel='icon' href='/favicon.ico' />
        <link rel="stylesheet" href="https://use.typekit.net/xid4pyt.css"/>
      </Head>
      <main>
        <Footer />
      </main>
    </div>
  );
}
